"""Added message table

Revision ID: 250aebe9416a
Revises: 9ef2d5b90533
Create Date: 2022-11-29 12:21:52.117588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250aebe9416a'
down_revision = '9ef2d5b90533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('class_', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'class', ['class_'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'class_')
    # ### end Alembic commands ###
