"""Initial

Revision ID: 46f2f113d2cd
Revises: 1975ea83b712
Create Date: 2022-10-28 11:40:44.642336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f2f113d2cd'
down_revision = '1975ea83b712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
